# Generated by Django 4.2.2 on 2023-06-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Journal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The full name of the journal.",
                        max_length=256,
                        unique=True,
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        help_text="The abbreviated name of the journal.",
                        max_length=32,
                        unique=True,
                    ),
                ),
            ],
            options={
                "ordering": ("abbr", "name"),
            },
        ),
        migrations.AddField(
            model_name="bibtex",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Any extra notes about this bibtex entry.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="bibtex",
            name="doi",
            field=models.CharField(
                blank=True,
                help_text="The digital object identifier (DOI) of a journal article, conference paper, book chapter or book.",
                max_length=256,
                null=True,
                verbose_name="DOI",
            ),
        ),
        migrations.AlterField(
            model_name="bibtex",
            name="isbn",
            field=models.CharField(
                blank=True,
                help_text="The International Standard Book Number (ISBN) of a book or report.",
                max_length=64,
                null=True,
                verbose_name="ISBN",
            ),
        ),
        migrations.AlterField(
            model_name="bibtex",
            name="issn",
            field=models.CharField(
                blank=True,
                help_text="The International Standard Serial Number (ISSN) of a journal or magazine.",
                max_length=64,
                null=True,
                verbose_name="ISSN",
            ),
        ),
    ]
