# Generated by Django 4.2.2 on 2023-06-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0002_journal_bibtex_notes_alter_bibtex_doi_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bibtex",
            old_name="howpublished",
            new_name="how_published",
        ),
    ]
