# Generated by Django 4.2.2 on 2023-06-30 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0003_rename_howpublished_bibtex_how_published"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibtex",
            name="journal",
            field=models.ForeignKey(
                blank=True,
                help_text="The journal or magazine the article was published in.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="literature.journal",
            ),
        ),
    ]
