# Generated by Django 4.2.2 on 2023-07-04 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0004_alter_bibtex_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibtex',
            name='abstract',
            field=models.TextField(blank=True, help_text="The paper's abstract.", null=True),
        ),
    ]
