# Generated by Django 4.2.2 on 2023-06-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulsar",
            name="catalogue_version",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
