# Generated by Django 4.2.2 on 2023-06-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_pulsar_catalogue_version"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="pulsar",
            constraint=models.UniqueConstraint(
                fields=("bname", "jname"), name="unique_names"
            ),
        ),
    ]
