# Generated by Django 4.2.2 on 2023-06-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_pulsar_unique_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pulsar",
            name="bname",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="pulsar",
            name="jname",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
