# Generated by Django 4.2.2 on 2023-06-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_spectrummodel_spectrummodelparameter_spectralfit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="spectrummodel",
            name="pulsar_spectra_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
