# Generated by Django 4.2.2 on 2023-06-11 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_spectrummodel_pulsar_spectra_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="spectralfit",
            unique_together={("pulsar", "parameter")},
        ),
        migrations.AlterUniqueTogether(
            name="spectrummodelparameter",
            unique_together={("spectral_model", "name")},
        ),
    ]
