# Generated by Django 4.2.2 on 2023-06-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_spectralfit_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spectrummodelparameter",
            options={"ordering": ("spectrum_model", "name")},
        ),
        migrations.RenameField(
            model_name="spectrummodelparameter",
            old_name="spectral_model",
            new_name="spectrum_model",
        ),
        migrations.AlterUniqueTogether(
            name="spectrummodelparameter",
            unique_together={("spectrum_model", "name")},
        ),
    ]
