# Generated by Django 4.2.2 on 2023-06-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_spectrummodelparameter_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spectrummodel",
            name="pulsar_spectra_name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
