# Generated by Django 4.2.2 on 2023-06-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_spectrummodel_pulsar_spectra_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATNFFluxMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freq', models.FloatField(help_text='The frequency in MHz')),
                ('flux', models.FloatField(help_text='The flux density in mJy')),
                ('pulsar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atnf_flux_measurements', to='core.pulsar')),
            ],
            options={
                'verbose_name': 'ATNF flux measurement set',
                'verbose_name_plural': 'ATNF flux measurement sets',
                'ordering': ('pulsar', 'freq'),
            },
        ),
    ]
