# Generated by Django 4.2.2 on 2023-06-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_atnffluxmeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='atnffluxmeasurement',
            name='error',
            field=models.FloatField(blank=True, help_text='The error on the flux density in mJy', null=True),
        ),
    ]
