# Generated by Django 4.2.2 on 2023-06-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_atnffluxmeasurement_error'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='atnffluxmeasurement',
            constraint=models.UniqueConstraint(fields=('pulsar', 'freq'), name='unique_pulsar_freq'),
        ),
    ]
