# Generated by Django 4.2.2 on 2023-06-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_atnffluxmeasurement_unique_pulsar_freq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrummodel',
            name='pulsar_spectra_name',
            field=models.CharField(help_text='The name used to identify the functional form (as implemented in pulsar_sectra).', max_length=128),
        ),
    ]
