# Generated by Django 4.2.2 on 2023-06-23 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_author_authororder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authororder",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_orders",
                to="core.author",
            ),
        ),
        migrations.AlterField(
            model_name="authororder",
            name="bibtex",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_orders",
                to="core.bibtex",
            ),
        ),
    ]
