# Generated by Django 4.2.2 on 2023-06-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_pulsarproperty_pulsarpropertymeasurement"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulsarproperty",
            name="symbol",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
