# Generated by Django 4.2.2 on 2023-06-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_pulsarproperty_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulsarpropertymeasurement",
            name="bandwidth_MHz",
            field=models.FloatField(
                blank=True,
                help_text="The frequency bandwidth with which this measurement was made.",
                null=True,
                verbose_name="Bandwidth (MHz)",
            ),
        ),
        migrations.AddField(
            model_name="pulsarpropertymeasurement",
            name="date",
            field=models.DateTimeField(
                blank=True,
                help_text="The (UTC) date/time at which the measurement was made.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="pulsarpropertymeasurement",
            name="freq_MHz",
            field=models.FloatField(
                blank=True,
                help_text="The (centre) frequency at which this measurement was made.",
                null=True,
                verbose_name="Frequency (MHz)",
            ),
        ),
        migrations.AddField(
            model_name="pulsarpropertymeasurement",
            name="time_span_s",
            field=models.FloatField(
                blank=True,
                help_text="The time span of the data used to make this measurement.",
                null=True,
                verbose_name="Time span (s)",
            ),
        ),
    ]
