# Generated by Django 4.2.2 on 2023-06-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_pulsarpropertymeasurement_bandwidth_mhz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pulsarpropertymeasurement",
            name="date",
        ),
        migrations.AddField(
            model_name="pulsarpropertymeasurement",
            name="mjd",
            field=models.DateTimeField(
                blank=True,
                help_text="The MJD when the measurement was made.",
                null=True,
            ),
        ),
    ]
