# Generated by Django 4.2.2 on 2023-06-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_remove_pulsarpropertymeasurement_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pulsarpropertymeasurement",
            name="mjd",
            field=models.FloatField(
                blank=True,
                help_text="The MJD when the measurement was made.",
                null=True,
            ),
        ),
    ]
