# Generated by Django 4.2.2 on 2023-06-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_pulsarpropertymeasurement_mjd"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="authororder",
            constraint=models.UniqueConstraint(
                fields=("bibtex", "order"), name="well_determined_order"
            ),
        ),
    ]
