# Generated by Django 4.2.2 on 2023-06-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_authororder_well_determined_order"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="authororder",
            name="well_determined_order",
        ),
        migrations.AddConstraint(
            model_name="authororder",
            constraint=models.UniqueConstraint(
                fields=("bibtex", "order"), name="well_determined_author_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="editororder",
            constraint=models.UniqueConstraint(
                fields=("bibtex", "order"), name="well_determined_editor_order"
            ),
        ),
    ]
