# Generated by Django 4.2.2 on 2023-06-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_pulsarpropertymeasurement_error_low_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pulsarpropertymeasurement",
            name="mode",
            field=models.CharField(
                blank=True,
                help_text="The mode, if any, to which this measurement applies.",
                max_length=16,
                null=True,
            ),
        ),
    ]
