# Generated by Django 4.2.2 on 2023-06-30 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("literature", "0001_initial"),
        ("core", "0028_pulsarpropertymeasurement_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pulsarpropertymeasurement",
            name="bibtex",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="literature.bibtex"
            ),
        ),
    ]
