# Generated by Django 4.2.2 on 2023-06-30 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_pulsarpropertymeasurement_bibtex"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AuthorOrder",
        ),
        migrations.DeleteModel(
            name="EditorOrder",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Bibtex",
        ),
    ]
