# Generated by Django 4.2.2 on 2023-07-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_authororder_author_remove_authororder_bibtex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsar',
            name='pdot',
            field=models.FloatField(blank=True, null=True, verbose_name='Period derivative (s/s)'),
        ),
    ]
