# Generated by Django 4.2.2 on 2023-07-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_pulsar_pdot'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsarproperty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
