# Generated by Django 4.2.2 on 2023-07-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_pulsarpropertymeasurement_is_lower_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsarpropertymeasurement',
            name='notes',
            field=models.TextField(blank=True, help_text='Any extra notes about this measurement.', null=True),
        ),
    ]
